HOMONYMS = {
    'above': ['about', 'out of'],
    'begin': ['began'],
    'camel': ['kimmel'],
    'copy': ['coffee'],
    'cut': ['collect'],
    'fish': ['dish', 'dished', 'pitch', 'finished'],
    'grab': ['lab', 'crab'],
    'high': ['hi', 'i'],
    'lend': ['land', 'lender'],
    'lit': ["let's", 'wet'],
    'mod': ['modest'],
    'perl': ['pearl', 'rural', 'moral', 'all'],
    'right': ['rights'],
    'select': ['selected'],
    'tab': ['have'],
    'wave': ['dave'],
    'wine': ['line'],
}