HOMONYMS = {
    'above': ['about', 'out of'],
    'begin': ['began'],
    'camel': ['kimmel'],
    'copy': ['coffee', 'copies'],
    'cut': ['collect'],
    'fish': ['dish', 'dished', 'pitch', 'finished', 'fiction', 'page'],
    'grab': ['lab', 'crab'],
    'kill': ['killed', 'kills'],
    'high': ['hi', 'i'],
    'lend': ['land', 'lender'],
    'line': ['wine'],
    'lit': ["let's", 'wet'],
    'mod': ['modest'],
    'nerd': ['learned'],
    'perl': ['pearl', 'rural', 'moral', 'all'],
    'right': ['rights'],
    'select': ['selected'],
    'start': ['skirt', 'starts', 'starting'],
    'tab': ['have'],
    'wave': ['dave'],
}