HOMONYMS = {
    'above': ['about', 'out of'],
    'begin': ['began'],
    'below': ['the low'],
    'braces': ['places', 'place', 'brace'],
    'camel': ['kimmel'],
    'copy': ['coffee', 'copies'],
    'create': ['creates'],
    'cut': ['collect'],
    'fish': ['dish', 'dished', 'pitch', 'finished', 'fiction', 'page'],
    'grab': ['lab', 'crab'],
    'kill': ['killed', 'kills'],
    'high': ['hi', 'i'],
    'lend': ['land', 'lender'],
    'line': ['wine'],
    'list': ['west'],
    'lit': ["let's", 'wet'],
    'mod': ['modest'],
    'nerd': ['learned', 'third', 'noted'],
    'perl': ['pearl', 'rural', 'moral', 'all'],
    'recur': ['occur', 'weaker'],
    'right': ['rights'],
    'select': ['selected'],
    'start': ['skirt', 'starts', 'starting', 'started'],
    'stop': ['stopped', 'stops'],
    'tab': ['have'],
    'wave': ['dave', 'ways'],
}